name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install PowerShell
      run: sudo apt-get update && sudo apt-get install -y powershell

    - name: Publish Module to PowerShell Gallery
      uses: pcgeek86/publish-powershell-module-action@v20
      with:
        NuGetApiKey: ${{ secrets.PS_GALLERY_API_KEY }}