name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Setup PowerShell
      uses: dahlbyk/setup-powershell@v1
    - name: Install required modules
      run: Install-Module -Name PowerShellGet -Force -SkipPublisherCheck -Scope CurrentUser
    - name: Publish to PSGallery
      run: |
        $psGalleryApiKey = "${{ secrets.PS_GALLERY_API_KEY }}"
        Publish-Module -Path './DiscordSlashManager' -NuGetApiKey $psGalleryApiKey -Repository PSGallery -Force