name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install required modules
      run: pwsh -Command "Install-Module -Name PowerShellGet -Force -SkipPublisherCheck -Scope CurrentUser"

    - name: Publish to PSGallery
      run: pwsh -Command "Publish-Module -Path './' -NuGetApiKey '${{ secrets.PS_GALLERY_API_KEY }}' -Repository PSGallery -Force"