name: Publish to PowerShell Gallery

on:
  push:
    branches:
      - main  # Replace with your default branch if not 'main'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup PowerShell
      uses: actions/setup-powershell@v1
      with:
        powershell-version: '7.1.3'

    - name: Publish Module to PowerShell Gallery
      run: |
        Install-Module -Name PowerShellGet -Force -SkipPublisherCheck
        $psGalleryApiKey = "${{ secrets.PS_GALLERY_API_KEY }}"
        Publish-Module -Path './' -NuGetApiKey $psGalleryApiKey -Repository PSGallery -Force